Reduced number of steps for non-CI push. Added a few methods on Cards for filtering. One working approach to load bots from the user cwd.

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -46,14 +46,17 @@ jobs:
     if: "!contains(github.event.head_commit.message, 'Trigger CI')"
     runs-on: ubuntu-latest
     steps:
-      - name: Step 1
-        id: PR-check
-        run: echo ::set-output name=status::pending
-        continue-on-error: true
-      - name: Dump steps context
-        env:
-          STEPS_CONTEXT: ${{ toJson(steps) }}
-        run: echo "$STEPS_CONTEXT"
-      - name: Check on failures
-        if: steps.PR-check.outputs.status == 'pending'
-        run: exit 1
+      # - name: Step 1
+      #   id: PR-check
+      #   run: echo ::set-output name=status::pending
+      #   continue-on-error: true
+      # - name: Dump steps context
+      #   env:
+      #     STEPS_CONTEXT: ${{ toJson(steps) }}
+      #   run: echo "$STEPS_CONTEXT"
+      # - name: Check on failures
+      #   if: steps.PR-check.outputs.status == 'pending'
+      #   run: exit 1
+      - name:
+         run: echo "Tests and checks skipped"
+         run: exit 1
